

------------------------------DATA PREPERATION AND UNDERSTANDING---------------------------------



---QUES1 What is the total number of rows in each of the 3 tables in the database

	SELECT COUNT(*) AS ROW_COUNT FROM Customer
	UNION ALL 
	SELECT COUNT(*) FROM Transactions
	UNION ALL
	SELECT COUNT(*) FROM prod_cat_info

---QUES2 WHAT IS THE TOTAL NUMBER OF TTRANSACTION THAT HAVE A RETURN?

SELECT COUNT(Qty) AS RETURN_ORDERS FROM Transactions
WHERE QTY<0

---QUES3 As you would have noticed , the dates provided across the dataset are not in a correct format .
--- as first step please convert the date variables into valid date formats before proceeding ahead 

select format(convert(DATE,DOB,105),'dd-MM-yyyy')as DOB_NEW from Customer

SELECT FORMAT(CONVERT(DATE,tran_date,105),'dd-MM-yyyy') as tran_date_new FROM Transactions


---QUES4 What is the time range of the transaction data available for analysis? 
-------- Show the output in number of days ,monthsand year simultaneously in different columns 

SELECT DISTINCT 
DATEDIFF(YEAR,(SELECT MIN(tran_date) from Transactions),(SELECT MAX(tran_date)from transactions)) TIME_RANGE_YEAR,
DATEDIFF(MONTH,(SELECT MIN(tran_date) from Transactions),(SELECT MAX(tran_date)from transactions)) TIME_RANGE_MONTH,
DATEDIFF(DAY,(SELECT MIN(tran_date) from Transactions),(SELECT MAX(tran_date)from transactions)) TIME_RANGE_DAY
FROM Transactions

---QUES5 Which product category does the the sub_category "DIY" BELONG TO ?

SELECT prod_cat FROM prod_cat_info
WHERE prod_subcat = 'DIY'

------------------------------DATA ANALYSIS ---------------------------------

---QUES1 WHICH CHANNEL IS MOST FREQUENTLY USED FOR TRANSACTIONS 

SELECT TOP 1 Store_type AS CHANNEL ,COUNT(Store_type) AS CHANNEL_COUNT  FROM Transactions
GROUP BY  Store_type
ORDER BY COUNT(Store_type) DESC


---QUES2 WHAT IS THE COUNT OF MALE AND FEMALE CUSTOMERS  IN THE DATABASE 

SELECT 
(SELECT COUNT(*) FROM CUSTOMER WHERE GENDER = 'M') AS MALE_COUNT,
(SELECT COUNT(*)FROM CUSTOMER WHERE GENDER = 'F') AS FEMALE_COUNT


---QUES3 FROM WHICH CITY WE HAVE MAXIMUM NUMER OF CUSTOMERS AND HOW MANY ?

SELECT TOP 1 city_code,COUNT(city_code) FROM CUSTOMER 
GROUP BY city_code
ORDER BY COUNT(city_code) DESC 

---QUES4 HOW MANY SUB_CATEGORY ARE THE UNDER THE BOOKS ?

SELECT prod_cat,prod_subcat  FROM prod_cat_info
where prod_cat = 'Books'

---QUES5 WHAT IS THE MAXIMUM NUMBER OF QUANTITY EVER ORDERED

SELECT MAX(QTY) AS MAX_QUANTITY FROM Transactions

---Ques6 WHAT IS THE NET TOTAL REVENUE GENERATED IN CATEGORIES ELECTRONICS AND BOOKS?

SELECT P.prod_cat AS PRODUCT_CAT,SUM(total_amt - Tax) AS TOTAL_REVENUE FROM Transactions AS T 
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code 
				AND 
	T.prod_subcat_code = P.prod_sub_cat_code 
WHERE P.prod_cat LIKE 'ELECTRONICS'  
GROUP BY P.prod_cat

UNION 

SELECT P.prod_cat AS PRODUCT_CAT,SUM(total_amt - Tax) AS TOTAL_REVENUE FROM Transactions AS T 
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code 
						AND 
	T.prod_subcat_code = P.prod_sub_cat_code 
WHERE P.prod_cat LIKE 'BOOKS'  
GROUP BY P.prod_cat

---QUES7 HOW MANY CUSTOMERS HAVE MORE THAN 10 TRANSACTIONS WITH US , EXCLUDING RETURNS ?

SELECT C.customer_Id AS CUSTOMER_ID,COUNT(T.cust_id) AS [TRANSACTIONS>10] FROM Customer AS C 
INNER JOIN Transactions AS T
ON C.customer_Id = T.cust_id
WHERE T.Qty > 0 
GROUP BY C.customer_Id
HAVING COUNT(T.cust_id) > 10

---QUES8 WHAT IS THE COMBINED REVENUE EARNED FROM THE "ELECTRONICS" & "CLOTHING" CATEGORIES , FROM  "FLAGSHIP STORES"

-------METHOD 1 
SELECT
sum(case when P.prod_cat LIKE 'ELECTRONICS' THEN T.RATE * T.QTY ELSE 0 END +
CASE WHEN P.prod_cat LIKE 'CLOTHING' THEN T.RATE * T.QTY ELSE 0 END ) AS [REVENUE_ELECTRO+CLOTHING]
from Transactions as T 
inner join prod_cat_info as P
ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE T.Store_type LIKE 'FLAGSHIP STORE'

-----METHOD 2 ----
SELECT
(SELECT SUM(T.Rate*T.QTY) AS REVENUE_ELECTRO FROM Transactions AS T 
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE P.prod_cat LIKE 'ELECTRONICS' AND T.Store_type LIKE 'FLAGSHIP STORE') 
+
(SELECT SUM(T.Rate*T.QTY) AS REVENUE_CLOTHI FROM Transactions AS T 
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE P.prod_cat LIKE 'CLOTHING' AND T.Store_type LIKE 'FLAGSHIP STORE' )
AS [REVENUE_ELECTRO+CLOTHI]


---QUES9 WHAT IS THE TOTAL REVENUE GENERATED BY "MALE" CUSTOMERS IN "ELECTRONICS" CATEGORY ?
---		 OUTPUT SHOULD DISPLAY TOTAL REVENUE BY	PROD_SUB_CAT.

SELECT P.prod_subcat AS SUBCATEGORY ,SUM(T.Rate * T.Qty) AS TOTAL_REVENUE FROM CUSTOMER AS C
INNER JOIN Transactions AS T 
ON C.customer_Id = T.cust_id
INNER JOIN prod_cat_info AS P
ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE C.Gender LIKE 'M' AND P.prod_cat LIKE 'ELECTRONICS'
GROUP BY P.prod_subcat

---QUES10 WHAT PERCENTAGE OF SALES AND RETURN BY PRODUCT SUB CATEGORY; 
---		   DISPLAY ONLY TOP 5 SUB CATEGORIES IN TERMS OF SALES?

SELECT TOP 5 
    P.prod_subcat AS SUB_CATEGORY,
    (SUM(T.total_amt) / (SELECT SUM(total_amt) FROM Transactions)) * 100 AS SALES_PERCENTAGE,
    (SUM(T.Qty) / (SELECT SUM(Qty) FROM Transactions)) * 100 AS RETURN_PERCENT
FROM Transactions AS T 
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code 
AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE T.QTY < 0
GROUP BY P.prod_subcat
ORDER BY SUM(T.total_amt) DESC;



---QUES11 FOR ALL CUSTOMERS AGED BTW 25 TO 35 YEARS FIND WHAT IS THE NET TOTAL REVENUE GENERATED 
---		  BY THESE CONSUMERS IN LAST 30 DAYS OF TRANSACTIONS FROM MAX TRANSACTION DATE AVAILABLE IN DATA ?

SELECT sum(total_amt) as TOTAL_SALES FROM Transactions AS T
INNER JOIN Customer AS c
ON T.cust_id =C.customer_Id 
WHERE DATEDIFF(YEAR,C.DOB,GETDATE()) BETWEEN 25 AND 35
			AND 
	 DATEDIFF(DAY,T.tran_date, (SELECT max(TRAN_DATE) FROM Transactions)) BETWEEN 0 AND 30

---QUES12 WHICH PRODUCT CATEGORY HAS SEEN THE MAX VALUE OF RETURNS IN THE LAST 3 MONTHS OF TRANSACTIONS?

SELECT TOP 1 P.prod_cat,COUNT(QTY) AS [RETURN]
FROM Transactions AS T 
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code AND 
	T.prod_subcat_code = P.prod_sub_cat_code
WHERE QTY<0 AND T.tran_date BETWEEN DATEADD(MONTH,-3,(SELECT max(TRAN_DATE) FROM Transactions)) AND (SELECT max(TRAN_DATE) FROM Transactions)
GROUP BY P.prod_cat
ORDER BY COUNT(QTY) DESC

---QUES13 WHICH STORE_TYPE SELLS THE MAXIMUM PRODUCTS ; BY VALUE OF SALES AMOUNT AND BY QUANTITY SOLD ?

SELECT Store_type,COUNT(prod_cat_code) AS PROD_COUNT,SUM(total_amt) AS SALES_AMT , SUM(QTY) AS QTY FROM Transactions
GROUP BY Store_type
ORDER BY COUNT(prod_cat_code) DESC

---QUES14 WHAT ARE THE CATEGORIES FOR WHICH AVERAGE REVENUE IS ABOVE THE OVERALL AVERAGE 

SELECT P.prod_cat AS PRODUCT_CATEGORY , AVG(T.total_amt - T.Tax) AS CAT_AVG_REV 
,(SELECT AVG(total_amt - TAX) FROM Transactions) AS OVERALL_AVG
FROM prod_cat_info AS P 
INNER JOIN Transactions AS T 
ON P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code = T.prod_subcat_code
GROUP BY P.prod_cat
HAVING AVG(T.total_amt - T.Tax) > (SELECT AVG(total_amt - Tax) FROM Transactions)

---QUES15 FIND THE AVERAGE AND TOTAL REVENUE BY EACH SUBCATEGORY FOR THE CATEGORIES 
---		  WHICH ARE AMONG TOP 5 CATEGORIES IN TERMS OF QUANTITY SOLD

--- METHOD 1 

SELECT TOP 5 P.prod_cat , P.prod_subcat,AVG(T.total_amt) AS AVERAGE, SUM(total_amt-Tax) AS TOTAL_REVENUE FROM prod_cat_info AS P
INNER JOIN Transactions AS T
ON P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code = T.prod_subcat_code
GROUP BY P.prod_cat , P.prod_subcat
ORDER BY SUM(T.Qty) DESC


---METHOD 2 

-- Step 1: Get top 5 categories by quantity
WITH TopCategories AS (
    SELECT TOP 5 P.prod_cat
    FROM Transactions T
    INNER JOIN prod_cat_info P
    ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
    GROUP BY P.prod_cat
    ORDER BY SUM(T.Qty) DESC
)

-- Step 2: Calculate average and total revenue by subcategory for those top categories
SELECT TOP 5
    P.prod_cat,
    P.prod_subcat,
    AVG(T.total_amt) AS AVERAGE_REVENUE,
    SUM(T.total_amt - T.Tax) AS TOTAL_REVENUE
FROM Transactions T
INNER JOIN prod_cat_info P
ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE P.prod_cat IN (SELECT prod_cat FROM TopCategories)
GROUP BY P.prod_cat, P.prod_subcat
ORDER BY  TOTAL_REVENUE DESC , AVERAGE_REVENUE DESC

